alias ytdl-audio='youtube-dl --extract-audio'
alias matlab-cli='matlab -nosplash -nodesktop'
alias ranger='ranger --choosedir=$HOME/.rangerdir; cd "$(cat $HOME/.rangerdir)"'
alias mpv='mpv --no-audio-display'
alias tlmgr='tlmgr --verify-repo=none --no-persistent-downloads'
alias latexmk='latexmk -pdf -halt-on-error'
alias neofetch='neofetch --ascii_distro Ubuntu-MATE'
alias rsync='rsync --archive --verbose --human-readable --progress'
alias cp='cp --verbose --interactive'
alias mv='mv --verbose --interactive'
alias rm='rm --verbose --interactive'
alias rg='rg --smart-case'
