#!/usr/bin/env bash
# This script deletes auxiliary files created by TeX.
# While it provides a similar functionality as "latexmk -c" command,
#     it deals with "eps-converted-to.pdf" files as well.
# Written in bash 5.0 by Jaewon Lee.

clear_exts=('aux' 'bbl' 'bcf' 'blg' 'fdb_latexmk' 'fls' 'log' 'nav' 'out' \
  'run.xml' 'snm' 'synctex(busy)' 'synctex.gz' 'toc')

recursive=false
silent=false

while [[ $# -gt 0 ]]
do
  case $1 in
    -r|--recursive)
      recursive=true
      ;;
    -s|--silent)
      silent=true
      ;;
    -sr|-rs)
      recursive=true
      silent=true
      ;;
    *)
      echo "Unknown option: $1" >&2
      exit 1
  esac
  shift
done

if $recursive; then maxdepth=99; else maxdepth=1; fi

if ! $silent; then echo "Removing..."; fi

find . -maxdepth $maxdepth -type f -iname '*.tex' -print0 \
  | while read -d '' texfile
do
  for ext in "${clear_exts[@]}"
  do
    filename="${texfile%.tex}.$ext"
    if [[ -f "$filename" ]]
    then
      if ! $silent; then echo "$filename"; fi
      trash "$filename"
    fi
  done
done

find . -maxdepth $maxdepth -type f -iname '*.eps' -print0 \
  | while read -d '' epsfile
do
  filename="${epsfile%.eps}-eps-converted-to.pdf"
  if [[ -f "$filename" ]]
  then
    if ! $silent; then echo "$filename"; fi
    trash "$filename"
  fi
done

if ! $silent; then echo "Done."; fi
