#!/usr/bin/env bash

# To reset the configuration, run the following:
# dconf reset -f /org/mate/terminal/

mate_profile="[profiles/default]
visible-name='Default'
copy-selection=true
use-system-font=false
use-theme-colors=false
scrollbar-position='hidden'
default-show-menubar=false
font='Monospace 16'
allow-bold=true"

# themes are from http://terminal.sexy
case $1 in
  default)
    mate_profile="$mate_profile
palette='#151515:#ac4142:#90a959:#f4bf75:#6a9fb5:#aa759f:#75b5aa:#d0d0d0:#505050:#ac4142:#90a959:#f4bf75:#6a9fb5:#aa759f:#75b5aa:#f5f5f5'
background-color='#151515'
foreground-color='#d0d0d0'
bold-color='#d0d0d0'"
    ;;
  londontube)
    mate_profile="$mate_profile
palette='#231f20:#ee2e24:#00853e:#ffd204:#009ddc:#98005d:#85cebc:#d9d8d8:#737171:#ee2e24:#00853e:#ffd204:#009ddc:#98005d:#85cebc:#ffffff'
background-color='#231f20'
foreground-color='#d9d8d8'
bold-color='#d9d8d'"
    ;;
  railscasts)
    mate_profile="$mate_profile
palette='#2b2b2b:#da4939:#a5c261:#ffc66d:#6d9cbe:#b6b3eb:#519f50:#e6e1dc:#5a647e:#da4939:#a5c261:#ffc66d:#6d9cbe:#b6b3eb:#519f50:#f9f7f3'
background-color='#2d2d2d'
foreground-color='#e6e1dc'
bold-color='#e6e1dc'"
    ;;
  *)
    echo "Applying default theme."
    echo "Available themes: default, londontube, railscasts."
    conf-mate-terminal default
    exit
    ;;
esac

echo "$mate_profile" | dconf load /org/mate/terminal/
