#!/usr/bin/env bash
# This script shows processes that use CPU and memory most heavily.
# Use -n or --nofity option to show it as a notification.

output="$(ps axc -o comm:15,%cpu,%mem --sort=-%cpu | head -6)

$(ps axc -o comm:15,%mem,%cpu --sort=-%mem | head -6)"

if [[ $1 =~ -n|--notify ]]
then
  notify-send 'CPU and memory usage' "<tt>$output</tt>"
else
  echo "$output"
fi
