#!/usr/bin/env bash
# print temperature and memory usage; perhaps useful for desktop panel

hash syncthing >/dev/null 2>&1 && { # if syncthing exists
  log=$(awk -F ';' 'END {print $1}' ~/Sync/raspi-log | xargs -0 date +%s -d)
  now=$(date +%s)
  if [[ $((($now - $log) / 60)) -gt 20 ]] # check if the server is on
  then
    echo -n "Sync: Off  "
  else # check if syncthing is running
    pgrep -c syncthing | awk '{ printf "Sync: %s  ", ($1 > 0 ? "On" : "Off") }'
  fi
}

# temperature
sensors -u | awk '
BEGIN              { temp = 0 }
/temp[0-9]*_input/ { temp = ($2 > temp) ? $2 : temp }
END                { printf "%.1f°C  ", temp }
'

# memory usage
free -m | awk '
/^Mem:/ {
  used = $3 + $5; free = $2
  used = (used >= 1000) ? sprintf("%.2fG", used / 1000) \
                        : sprintf("%dM", used)
  free = sprintf("%.2fG", free / 1000)
  print used "/" free
}
'
